---
deployment:
  tasks:
    - |
      echo "==== Virtuous Ensemble: deploy iniciado ===="
      export DEPLOYPATH=/home/virtuou1/public_html/
      export APPROOT=/home/virtuou1/repositories/virtuous-harmony-hub
      cd $APPROOT
      
      # Encontrar npm
      if command -v npm >/dev/null 2>&1; then
        NPM_CMD=npm
      elif [ -x /opt/cpanel/ea-nodejs20/bin/npm ]; then
        NPM_CMD=/opt/cpanel/ea-nodejs20/bin/npm
      elif [ -x /opt/cpanel/ea-nodejs18/bin/npm ]; then
        NPM_CMD=/opt/cpanel/ea-nodejs18/bin/npm
      elif [ -x /usr/local/bin/npm ]; then
        NPM_CMD=/usr/local/bin/npm
      else
        echo "ERRO: npm não encontrado. Configure Node.js no cPanel."
        exit 1
      fi
      
      echo "Usando npm: $NPM_CMD"
      $NPM_CMD ci
      CI=false $NPM_CMD run build
      
      # Criar 404.html e .htaccess para SPA
      cp -f dist/index.html dist/404.html
      cat > dist/.htaccess << 'EOF'
      RewriteEngine On
      RewriteBase /
      RewriteCond %{REQUEST_FILENAME} !-f
      RewriteCond %{REQUEST_FILENAME} !-d
      RewriteRule . /index.html [L]
      EOF
      
      # Publicar em public_html
      echo "Publicando em $DEPLOYPATH"
      mkdir -p $DEPLOYPATH
      rm -rf $DEPLOYPATH/*
      cp -R dist/* $DEPLOYPATH/
      
      echo "==== Deploy concluído com sucesso ===="
