---
deployment:
  tasks:
    - |
      APPROOT="/home/virtuou2/repositories/virtuous-harmony-hub"
      DEPLOYPATH="/home/virtuou2/public_html"
      LOGFILE="$DEPLOYPATH/deploy_log.txt"
      
      # Função para log (salva no arquivo e mostra no ecrã)
      log() {
        echo "$1" | tee -a "$LOGFILE"
      }
      
      log "==== Virtuous Ensemble: deploy iniciado ===="
      log "APPROOT: $APPROOT"
      log "DEPLOYPATH: $DEPLOYPATH"
      log "LOGFILE: $LOGFILE"
      log "Data/Hora: $(date)"
      log ""
      
      # Verificar se o diretório do repositório existe
      if [ ! -d "$APPROOT" ]; then
        log "ERRO: Diretório $APPROOT não existe" | tee -a "$LOGFILE"
        exit 1
      fi
      
      cd "$APPROOT" || { log "ERRO: Não foi possível aceder a $APPROOT" | tee -a "$LOGFILE"; exit 1; }
      log "Diretório atual: $(pwd)"
      
      # Remover arquivos não rastreados que podem causar conflito no merge
      log "--- Verificando e removendo arquivos conflitantes ---"
      if [ -f "app.js" ] && ! git ls-files --error-unmatch app.js >/dev/null 2>&1; then
        log "Removendo app.js não rastreado (será substituído pela versão do repositório)"
        rm -f app.js || true
      fi
      log "Limpeza de arquivos conflitantes concluída"
      log ""
      
      # Tentar fazer build (mas continuar mesmo se falhar)
      log "--- Tentando fazer build do projeto ---"
      log "Procurando npm em várias localizações..."
      
      # Primeiro, tentar encontrar o ambiente virtual do Node.js criado pelo cPanel
      # O cPanel cria ambientes em: /home/USER/nodevenv/APP_ROOT/VERSION/bin/npm
      NODEVENV_BASE="/home/virtuou2/nodevenv/repositories/virtuous-harmony-hub"
      
      # Lista de possíveis localizações do npm no cPanel (prioridade: ambiente virtual > sistema)
      NPM_PATHS=(
        # Ambiente virtual do cPanel (versões mais recentes primeiro)
        "$NODEVENV_BASE/20/bin/npm"
        "$NODEVENV_BASE/18/bin/npm"
        "$NODEVENV_BASE/16/bin/npm"
        "$NODEVENV_BASE/*/bin/npm"
        # Sistema global
        "$(command -v npm 2>/dev/null)"
        "/opt/cpanel/ea-nodejs20/bin/npm"
        "/opt/cpanel/ea-nodejs18/bin/npm"
        "/opt/cpanel/ea-nodejs16/bin/npm"
        "/usr/local/bin/npm"
        "/usr/bin/npm"
        "$HOME/.nvm/versions/node/*/bin/npm"
      )
      
      NPM_CMD=""
      NODE_VERSION=""
      for npm_path in "${NPM_PATHS[@]}"; do
        # Expandir wildcards
        for expanded_path in $npm_path; do
          if [ -x "$expanded_path" ] 2>/dev/null; then
            NPM_CMD="$expanded_path"
            # Tentar obter a versão do Node.js
            NODE_BIN="$(dirname "$NPM_CMD")/node"
            if [ -x "$NODE_BIN" ]; then
              NODE_VERSION="$($NODE_BIN --version 2>/dev/null || echo 'unknown')"
            fi
            log "npm encontrado em: $NPM_CMD"
            log "Versão do Node.js: $NODE_VERSION"
            break 2
          fi
        done
      done
      
      # Verificar se a versão do Node.js é compatível (Vite 5 requer Node.js 18+)
      if [ -n "$NODE_VERSION" ]; then
        MAJOR_VERSION=$(echo "$NODE_VERSION" | cut -d. -f1 | sed 's/v//')
        if [ "$MAJOR_VERSION" -lt 18 ] 2>/dev/null; then
          log ""
          log "=========================================="
          log "ERRO: Versão do Node.js incompatível!"
          log "=========================================="
          log ""
          log "Versão encontrada: Node.js $NODE_VERSION"
          log "Versão necessária: Node.js 18 ou superior"
          log ""
          log "O Vite 5.4.19 requer Node.js 18+ para funcionar."
          log ""
          log "SOLUÇÃO: Atualizar a versão do Node.js no cPanel"
          log ""
          log "1. No cPanel, vá para 'Setup Node.js App'"
          log "2. Clique na sua aplicação (virtuousensemble.pt)"
          log "3. No campo 'Node.js version', mude de '10.24.1' para '18.x' ou '20.x'"
          log "4. Clique em 'SAVE'"
          log "5. Aguarde alguns segundos para o ambiente ser recriado"
          log "6. Execute o deploy novamente"
          log ""
          log "Este log foi salvo em: $LOGFILE"
          log "=========================================="
          exit 1
        fi
      fi
      
      if [ -z "$NPM_CMD" ]; then
        log "npm não encontrado em nenhuma localização padrão"
        log "Verificando se há Node.js instalado mas não acessível..."
        
        # Verificar se há Node.js instalado via cPanel mas não no PATH
        if [ -d "/opt/cpanel/ea-nodejs20" ]; then
          log "Node.js 20 encontrado em /opt/cpanel/ea-nodejs20 mas npm não acessível"
        elif [ -d "/opt/cpanel/ea-nodejs18" ]; then
          log "Node.js 18 encontrado em /opt/cpanel/ea-nodejs18 mas npm não acessível"
        fi
      fi
      
      if [ -n "$NPM_CMD" ]; then
        log "Usando npm: $NPM_CMD"
        log "Instalando dependências..."
        "$NPM_CMD" ci 2>&1 | tee -a "$LOGFILE" || { log "ERRO: npm ci falhou"; exit 1; }
        log "Fazendo build do projeto..."
        CI=false "$NPM_CMD" run build 2>&1 | tee -a "$LOGFILE" || { log "ERRO: npm run build falhou"; exit 1; }
        log "Build concluído com sucesso"
      else
        log ""
        log "=========================================="
        log "ERRO: npm não encontrado!"
        log "=========================================="
        log ""
        log "O build é necessário para gerar os arquivos JS/CSS."
        log ""
        log "INSTRUÇÕES PARA INSTALAR NODE.JS NO CPANEL:"
        log ""
        log "OPÇÃO 1 - Setup Node.js App (Interface do Usuário):"
        log "1. No cPanel, procure na barra de pesquisa (topo): 'Setup Node.js App'"
        log "2. Ou procure em: 'Software' → 'Setup Node.js App'"
        log "3. Ou procure em: 'Advanced' → 'Setup Node.js App'"
        log "4. Clique em 'Create Application'"
        log "5. Configure:"
        log "   - Node.js Version: escolha 18 ou 20"
        log "   - Application Root: /home/virtuou2/repositories/virtuous-harmony-hub"
        log "   - Application URL: (deixe em branco ou use um subdomínio)"
        log "   - Application Startup File: (não necessário para build)"
        log "6. Clique em 'Create'"
        log ""
        log "OPÇÃO 2 - Via WHM (se tiver acesso root):"
        log "1. Acesse o WHM (Web Host Manager)"
        log "2. Vá em: 'Software' → 'EasyApache 4'"
        log "3. Clique em 'Customize'"
        log "4. Na secção 'Additional Packages', selecione 'ea-nodejs18' ou 'ea-nodejs20'"
        log "5. Clique em 'Next' e depois 'Provision'"
        log ""
        log "OPÇÃO 3 - Contactar Suporte:"
        log "Se não encontrar 'Setup Node.js App', contacte o suporte do hosting"
        log "e peça para instalar Node.js 18 ou 20 no servidor."
        log ""
        log "Após instalar, o npm ficará disponível em:"
        log "   /opt/cpanel/ea-nodejs18/bin/npm ou"
        log "   /opt/cpanel/ea-nodejs20/bin/npm"
        log ""
        log "Este log foi salvo em: $LOGFILE"
        log "=========================================="
        exit 1
      fi
      
      # Verificar se dist existe e tem arquivos necessários
      log "--- Verificando diretório dist ---"
      if [ ! -d "dist" ]; then
        log "ERRO: Diretório dist não foi criado pelo build" | tee -a "$LOGFILE"
        exit 1
      fi
      
      log "Diretório dist encontrado"
      log "Conteúdo completo de dist:"
      ls -la dist/ | tee -a "$LOGFILE"
      
      # Verificar se há arquivos JS/CSS (necessários para o site funcionar)
      JS_COUNT=$(find dist -name "*.js" 2>/dev/null | wc -l)
      CSS_COUNT=$(find dist -name "*.css" 2>/dev/null | wc -l)
      
      log "Arquivos JavaScript encontrados: $JS_COUNT"
      log "Arquivos CSS encontrados: $CSS_COUNT"
      
      if [ "$JS_COUNT" -eq 0 ]; then
        log "ERRO: Nenhum arquivo JavaScript foi gerado pelo build!" | tee -a "$LOGFILE"
        log "O site não funcionará sem os arquivos JS." | tee -a "$LOGFILE"
        exit 1
      fi
      
      if [ ! -f "dist/index.html" ]; then
        log "ERRO: dist/index.html não existe" | tee -a "$LOGFILE"
        exit 1
      fi
      
      # Criar arquivos necessários para SPA
      if [ -f "dist/index.html" ]; then
        cp -f dist/index.html dist/404.html 2>/dev/null || true
        log "Criado 404.html"
      fi
      
      # Criar .htaccess
      cat > dist/.htaccess << 'EOF'
      RewriteEngine On
      RewriteBase /
      RewriteCond %{REQUEST_FILENAME} !-f
      RewriteCond %{REQUEST_FILENAME} !-d
      RewriteRule . /index.html [L]
      EOF
      log "Criado .htaccess"
      
      # Verificar permissões de escrita em public_html
      log "--- Verificando permissões e preparando public_html ---"
      if [ ! -d "$DEPLOYPATH" ]; then
        log "Criando diretório $DEPLOYPATH"
        mkdir -p "$DEPLOYPATH" || { log "ERRO: Não foi possível criar $DEPLOYPATH" | tee -a "$LOGFILE"; exit 1; }
      fi
      
      # Testar escrita
      touch "$DEPLOYPATH/.write_test" 2>/dev/null && rm -f "$DEPLOYPATH/.write_test" && log "Permissões de escrita OK" || { log "ERRO: Sem permissão de escrita em $DEPLOYPATH" | tee -a "$LOGFILE"; exit 1; }
      
      # Limpar public_html (mas preservar o log)
      log "--- Limpando public_html ---"
      if [ -f "$DEPLOYPATH/.htaccess" ]; then
        mv "$DEPLOYPATH/.htaccess" "$DEPLOYPATH/.htaccess.backup"
      fi
      # Não remover o deploy_log.txt se existir
      if [ -f "$LOGFILE" ]; then
        mv "$LOGFILE" "$LOGFILE.old"
      fi
      rm -rf "$DEPLOYPATH"/* 2>/dev/null || true
      rm -rf "$DEPLOYPATH"/.[!.]* 2>/dev/null || true
      rm -rf "$DEPLOYPATH"/..?* 2>/dev/null || true
      # Restaurar o log antigo se existir
      if [ -f "$LOGFILE.old" ]; then
        mv "$LOGFILE.old" "$LOGFILE"
      fi
      log "public_html limpo"
      
      # Copiar arquivos
      log "--- Copiando arquivos de dist para public_html ---"
      if [ -d "dist" ] && [ "$(ls -A dist 2>/dev/null)" ]; then
        log "Copiando conteúdo de dist..."
        /bin/cp -R dist/. "$DEPLOYPATH"/ 2>&1 | tee -a "$LOGFILE" || { log "ERRO: Falha ao copiar arquivos" | tee -a "$LOGFILE"; exit 1; }
        log "Arquivos copiados com sucesso"
      else
        log "ERRO: Diretório dist está vazio ou não existe" | tee -a "$LOGFILE"
        exit 1
      fi
      
      # Verificar cópia
      log "--- Verificando arquivos copiados ---"
      log "Arquivos em public_html:"
      ls -la "$DEPLOYPATH" | tee -a "$LOGFILE"
      log ""
      log "Estrutura de diretórios em public_html:"
      find "$DEPLOYPATH" -type f | head -50 | tee -a "$LOGFILE"
      
      FILE_COUNT=$(find "$DEPLOYPATH" -type f | wc -l)
      JS_COUNT=$(find "$DEPLOYPATH" -name "*.js" | wc -l)
      CSS_COUNT=$(find "$DEPLOYPATH" -name "*.css" | wc -l)
      
      log ""
      log "Resumo da cópia:"
      log "  Total de arquivos: $FILE_COUNT"
      log "  Arquivos JavaScript: $JS_COUNT"
      log "  Arquivos CSS: $CSS_COUNT"
      
      if [ "$FILE_COUNT" -eq 0 ]; then
        log "ERRO: Nenhum arquivo foi copiado!" | tee -a "$LOGFILE"
        exit 1
      fi
      
      if [ "$JS_COUNT" -eq 0 ]; then
        log "AVISO: Nenhum arquivo JavaScript foi copiado. O site pode não funcionar corretamente." | tee -a "$LOGFILE"
      fi
      
      # Restaurar .htaccess se necessário
      if [ -f "$DEPLOYPATH/.htaccess.backup" ] && [ ! -f "$DEPLOYPATH/.htaccess" ]; then
        mv "$DEPLOYPATH/.htaccess.backup" "$DEPLOYPATH/.htaccess"
      fi
      
      log "==== Deploy concluído com sucesso ===="
      log ""
      log "=========================================="
      log "LOG COMPLETO SALVO EM: $LOGFILE"
      log "Pode aceder ao log através do File Manager:"
      log "  File Manager → public_html → deploy_log.txt"
      log "=========================================="
