---
deployment:
  tasks:
    - |
      echo "==== Virtuous Ensemble: deploy iniciado ===="
      
      APPROOT="/home/virtuou1/repositories/virtuous-harmony-hub"
      DEPLOYPATH="/home/virtuou1/public_html"
      
      echo "APPROOT: $APPROOT"
      echo "DEPLOYPATH: $DEPLOYPATH"
      
      # Verificar se o diretório do repositório existe
      if [ ! -d "$APPROOT" ]; then
        echo "ERRO: Diretório $APPROOT não existe"
        exit 1
      fi
      
      cd "$APPROOT" || { echo "ERRO: Não foi possível aceder a $APPROOT"; exit 1; }
      echo "Diretório atual: $(pwd)"
      
      # Tentar fazer build (mas continuar mesmo se falhar)
      echo "--- Tentando fazer build do projeto ---"
      if command -v npm >/dev/null 2>&1; then
        NPM_CMD=npm
      elif [ -x /opt/cpanel/ea-nodejs20/bin/npm ]; then
        NPM_CMD=/opt/cpanel/ea-nodejs20/bin/npm
      elif [ -x /opt/cpanel/ea-nodejs18/bin/npm ]; then
        NPM_CMD=/opt/cpanel/ea-nodejs18/bin/npm
      elif [ -x /usr/local/bin/npm ]; then
        NPM_CMD=/usr/local/bin/npm
      else
        echo "AVISO: npm não encontrado. Tentando copiar arquivos existentes..."
        NPM_CMD=""
      fi
      
      if [ -n "$NPM_CMD" ]; then
        echo "Usando npm: $NPM_CMD"
        "$NPM_CMD" ci || echo "AVISO: npm ci falhou, continuando..."
        CI=false "$NPM_CMD" run build || echo "AVISO: npm run build falhou, continuando..."
      fi
      
      # Verificar se dist existe ou criar estrutura básica
      echo "--- Verificando diretório dist ---"
      if [ -d "dist" ]; then
        echo "Diretório dist encontrado"
        echo "Conteúdo de dist:"
        ls -la dist/ | head -20
      else
        echo "AVISO: Diretório dist não existe. Criando estrutura básica..."
        mkdir -p dist
        if [ -f "index.html" ]; then
          cp index.html dist/
          echo "Copiado index.html para dist"
        fi
      fi
      
      # Criar arquivos necessários para SPA
      if [ -f "dist/index.html" ]; then
        cp -f dist/index.html dist/404.html 2>/dev/null || true
        echo "Criado 404.html"
      fi
      
      # Criar .htaccess
      cat > dist/.htaccess << 'EOF'
      RewriteEngine On
      RewriteBase /
      RewriteCond %{REQUEST_FILENAME} !-f
      RewriteCond %{REQUEST_FILENAME} !-d
      RewriteRule . /index.html [L]
      EOF
      echo "Criado .htaccess"
      
      # Verificar permissões de escrita em public_html
      echo "--- Verificando permissões e preparando public_html ---"
      if [ ! -d "$DEPLOYPATH" ]; then
        echo "Criando diretório $DEPLOYPATH"
        mkdir -p "$DEPLOYPATH" || { echo "ERRO: Não foi possível criar $DEPLOYPATH"; exit 1; }
      fi
      
      # Testar escrita
      touch "$DEPLOYPATH/.write_test" 2>/dev/null && rm -f "$DEPLOYPATH/.write_test" && echo "Permissões de escrita OK" || { echo "ERRO: Sem permissão de escrita em $DEPLOYPATH"; exit 1; }
      
      # Limpar public_html
      echo "--- Limpando public_html ---"
      if [ -f "$DEPLOYPATH/.htaccess" ]; then
        mv "$DEPLOYPATH/.htaccess" "$DEPLOYPATH/.htaccess.backup"
      fi
      rm -rf "$DEPLOYPATH"/* 2>/dev/null || true
      rm -rf "$DEPLOYPATH"/.[!.]* 2>/dev/null || true
      rm -rf "$DEPLOYPATH"/..?* 2>/dev/null || true
      echo "public_html limpo"
      
      # Copiar arquivos
      echo "--- Copiando arquivos de dist para public_html ---"
      if [ -d "dist" ] && [ "$(ls -A dist 2>/dev/null)" ]; then
        echo "Copiando conteúdo de dist..."
        /bin/cp -R dist/. "$DEPLOYPATH"/ || { echo "ERRO: Falha ao copiar arquivos"; exit 1; }
        echo "Arquivos copiados com sucesso"
      else
        echo "ERRO: Diretório dist está vazio ou não existe"
        exit 1
      fi
      
      # Verificar cópia
      echo "--- Verificando arquivos copiados ---"
      echo "Arquivos em public_html:"
      ls -la "$DEPLOYPATH" | head -30
      FILE_COUNT=$(find "$DEPLOYPATH" -type f | wc -l)
      echo "Total de arquivos copiados: $FILE_COUNT"
      
      if [ "$FILE_COUNT" -eq 0 ]; then
        echo "ERRO: Nenhum arquivo foi copiado!"
        exit 1
      fi
      
      # Restaurar .htaccess se necessário
      if [ -f "$DEPLOYPATH/.htaccess.backup" ] && [ ! -f "$DEPLOYPATH/.htaccess" ]; then
        mv "$DEPLOYPATH/.htaccess.backup" "$DEPLOYPATH/.htaccess"
      fi
      
      echo "==== Deploy concluído com sucesso ===="
